_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
langcode: uk
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    uk: ''
  domains:
    uk: ''
selected_langcode: site_default
