_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: uk
uuid: 4ed47cc1-eb70-432d-8077-3776957ac937
name: 'Мій Богуслав'
mail: myboguslavmybg@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /home
admin_compact_mode: false
weight_select_max: 100
default_langcode: uk
